### ISSUE TITLE
网盘链接挂了

### ISSUE THREAD

**Issue by ghost** [fumoliufenyi/-#2]
github对一个仓库的大小限制是1GB，如果没有超过限制，把pdf直接上传github是合理的。如果大小超过限制，bittorrent也可以作为分享手段。

**Comment by balthild** [comment]
分批上传到 GitHub Release 好像就没有这个限制。希望作者尝试一下，或者先放在一些国外的网盘，比如 Google Drive、Onedrive 等应急。
